--- #YAML:1.0
name:               Net-Subnet
version:            1.03
abstract:           Fast IP-in-subnet matcher for IPv4 and IPv6, CIDR or mask.
author:
    - Juerd Waalboer <#####@juerd.nl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Socket6:  0.23
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
